version: "3.7"
name: gameplan

services:
  mariadb:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  frappe:
    image: frappe/bench:latest
    command: bash /workspace/init.sh
    environment:
      SHELL: /bin/bash
      REDIS_CACHE: redis://redis:6379/0
      REDIS_QUEUE: redis://redis:6379/1
      REDIS_SOCKETIO: redis://redis:6379/2
    working_dir: /home/frappe
    volumes:
      - .:/workspace
    ports:
      - 8000:8000
      - 9000:9000
    depends_on:
      - mariadb
      - redis

volumes:
  mariadb-data:
